'type' object has no attribute error
Got this error and deleted the extra 'e' to fix it.

```
Traceback (most recent call last):
  File "ffproc.py", line 215, in <module>
    if fil[-4:]==".mpg" or file[-4:]==".vob": # These are usually OTA  recordings or DVD rips, which are in 1080i. There isn't a good way to test this.
TypeError: 'type' object has no attribute '__getitem__'
```